export const START_SAVE = "app/START_SAVE";
export const START_SEARCH = "app/START_SEARCH";

export const SET_SEARCH_PATIENT_IDS = "app/SET_SEARCH_PATIENT_IDS";
export const SET_SELECTED_PATIENT_ID = "app/SET_SELECTED_PATIENT_ID";
