export const START_SEARCH = "app/START_SEARCH";
export const START_SELECT = "app/START_SELECT";

export const SET_SEARCH_PATIENT_IDS = "app/SET_SEARCH_PATIENT_IDS";
export const SET_SELECTED_PATIENT_ID = "app/SET_SELECTED_PATIENT_ID";
